HEROES = [
    "0",
    '[Anti-Mage](/hero-antimage "Anti-Mage")',
    '[Axe](/hero-axe "Axe")',
    '[Bane](/hero-bane "Bane")',
    '[Bloodseeker](/hero-bloodseeker "Bloodseeker")',
    '[Crystal Maiden](/hero-crystalmaiden "Crystal Maiden")',
    '[Drow Ranger](/hero-drowranger "Drow Ranger")',
    '[Earthshaker](/hero-earthshaker "Earthshaker")',
    '[Juggernaut](/hero-juggernaut "Juggernaut")',
    '[Mirana](/hero-mirana "Mirana")',
    '[Morphling](/hero-morphling "Morphling")',
    '[Shadow Fiend](/hero-shadowfiend "Shadow Fiend")',
    '[Phantom Lancer](/hero-phantomlancer "Phantom Lancer")',
    '[Puck](/hero-puck "Puck")',
    '[Pudge](/hero-pudge "Pudge")',
    '[Razor](/hero-razor "Razor")',
    '[Sand King](/hero-sandking "Sand King")',
    '[Storm Spirit](/hero-stormspirit "Storm Spirit")',
    '[Sven](/hero-sven "Sven")',
    '[Tiny](/hero-tiny "Tiny")',
    '[Vengeful Spirit](/hero-vengefulspirit "Vengeful Spirit")',
    '[Windranger](/hero-windranger "Windranger")',
    '[Zeus](/hero-zeus "Zeus")',
    '[Kunkka](/hero-kunkka "Kunkka")',
    "24",
    '[Lina](/hero-lina "Lina")',
    '[Lion](/hero-lion "Lion")',
    '[Shadow Shaman](/hero-shadowshaman "Shadow Shaman")',
    '[Slardar](/hero-slardar "Slardar")',
    '[Tidehunter](/hero-tidehunter "Tidehunter")',
    '[Witch Doctor](/hero-witchdoctor "Witch Doctor")',
    '[Lich](/hero-lich "Lich")',
    '[Riki](/hero-riki "Riki")',
    '[Enigma](/hero-enigma "Enigma")',
    '[Tinker](/hero-tinker "Tinker")',
    '[Sniper](/hero-sniper "Sniper")',
    '[Necrophos](/hero-necrophos "Necrophos")',
    '[Warlock](/hero-warlock "Warlock")',
    '[Beastmaster](/hero-beastmaster "Beastmaster")',
    '[Queen of Pain](/hero-queenofpain "Queen of Pain")',
    '[Venomancer](/hero-venomancer "Venomancer")',
    '[Faceless Void](/hero-facelessvoid "Faceless Void")',
    '[Wraith King](/hero-wraithking "Wraith King")',
    '[Death Prophet](/hero-deathprophet "Death Prophet")',
    '[Phantom Assassin](/hero-phantomassassin "Phantom Assassin")',
    '[Pugna](/hero-pugna "Pugna")',
    '[Templar Assassin](/hero-templarassassin "Templar Assassin")',
    '[Viper](/hero-viper "Viper")',
    '[Luna](/hero-luna "Luna")',
    '[Dragon Knight](/hero-dragonknight "Dragon Knight")',
    '[Dazzle](/hero-dazzle "Dazzle")',
    '[Clockwerk](/hero-clockwerk "Clockwerk")',
    '[Leshrac](/hero-leshrac "Leshrac")',
    "[Nature's Prophet](/hero-naturesprophet \"Nature's Prophet\")",
    '[Lifestealer](/hero-lifestealer "Lifestealer")',
    '[Dark Seer](/hero-darkseer "Dark Seer")',
    '[Clinkz](/hero-clinkz "Clinkz")',
    '[Omniknight](/hero-omniknight "Omniknight")',
    '[Enchantress](/hero-enchantress "Enchantress")',
    '[Huskar](/hero-huskar "Huskar")',
    '[Night Stalker](/hero-nightstalker "Night Stalker")',
    '[Broodmother](/hero-broodmother "Broodmother")',
    '[Bounty Hunter](/hero-bountyhunter "Bounty Hunter")',
    '[Weaver](/hero-weaver "Weaver")',
    '[Jakiro](/hero-jakiro "Jakiro")',
    '[Batrider](/hero-batrider "Batrider")',
    '[Chen](/hero-chen "Chen")',
    '[Spectre](/hero-spectre "Spectre")',
    '[Ancient Apparition](/hero-ancientapparition "Ancient Apparition")',
    '[Doom](/hero-doom "Doom")',
    '[Ursa](/hero-ursa "Ursa")',
    '[Spirit Breaker](/hero-spiritbreaker "Spirit Breaker")',
    '[Gyrocopter](/hero-gyrocopter "Gyrocopter")',
    '[Alchemist](/hero-alchemist "Alchemist")',
    '[Invoker](/hero-invoker "Invoker")',
    '[Silencer](/hero-silencer "Silencer")',
    '[Outworld Devourer](/hero-outworlddevourer "Outworld Devourer")',
    '[Lycan](/hero-lycan "Lycan")',
    '[Brewmaster](/hero-brewmaster "Brewmaster")',
    '[Shadow Demon](/hero-shadowdemon "Shadow Demon")',
    '[Lone Druid](/hero-lonedruid "Lone Druid")',
    '[Chaos Knight](/hero-chaosknight "Chaos Knight")',
    '[Meepo](/hero-meepo "Meepo")',
    '[Treant Protector](/hero-treantprotector "Treant Protector")',
    '[Ogre Magi](/hero-ogremagi "Ogre Magi")',
    '[Undying](/hero-undying "Undying")',
    '[Rubick](/hero-rubick "Rubick")',
    '[Disruptor](/hero-disruptor "Disruptor")',
    '[Nyx Assassin](/hero-nyxassassin "Nyx Assassin")',
    '[Naga Siren](/hero-nagasiren "Naga Siren")',
    '[Keeper of the Light](/hero-keeperofthelight "Keeper of the Light")',
    '[Io](/hero-io "Io")',
    '[Visage](/hero-visage "Visage")',
    '[Slark](/hero-slark "Slark")',
    '[Medusa](/hero-medusa "Medusa")',
    '[Troll Warlord](/hero-trollwarlord "Troll Warlord")',
    '[Centaur Warrunner](/hero-centaurwarrunner "Centaur Warrunner")',
    '[Magnus](/hero-magnus "Magnus")',
    '[Timbersaw](/hero-timbersaw "Timbersaw")',
    '[Bristleback](/hero-bristleback "Bristleback")',
    '[Tusk](/hero-tusk "Tusk")',
    '[Skywrath Mage](/hero-skywrathmage "Skywrath Mage")',
    '[Abaddon](/hero-abaddon "Abaddon")',
    '[Elder Titan](/hero-eldertitan "Elder Titan")',
    '[Legion Commander](/hero-legioncommander "Legion Commander")',
    '[Techies](/hero-techies "Techies")',
    '[Ember Spirit](/hero-emberspirit "Ember Spirit")',
    '[Earth Spirit](/hero-earthspirit "Earth Spirit")',
    '[Underlord](/hero-abyssalunderlord "Underlord")',
    '[Terrorblade](/hero-terrorblade "Terrorblade")',
    '[Phoenix](/hero-phoenix "Phoenix")',
    '[Oracle](/hero-oracle "Oracle")',
    '[Winter Wyvern](/hero-winterwyvern "Winter Wyvern")',
    '[Arc Warden](/hero-arcwarden "Arc Warden")',
    '[Monkey King](/hero-monkeyking "Monkey King")',
    "115",
    "116",
    "117",
    "118",
    '[Dark Willow](/hero-darkwillow "Dark Willow")',
    '[Pangolier](/hero-pangolier "Pangolier")',
    '[Grimstroke](/hero-grimstroke "Grimstroke")',
    "122",
    "123",
    "124",
    "125",
    '[Void Spirit](/hero-voidspirit "Void Spirit")',
    "127",
    '[Snapfire](/hero-snapfire "Snapfire")',
    '[Mars](/hero-mars "Mars")',
]
